routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\HomeController;
use App\Http\Controllers\website\Auth\SignUpController;
use App\Http\Controllers\website\Auth\ResetPasswordController;
use App\Http\Controllers\website\Auth\loginController;
use App\Http\Controllers\website\Auth\ForgetPasswordController;
use App\Http\Controllers\website\DeviceController;
use App\Http\Controllers\website\CategoryController;
use App\Http\Controllers\website\SettingController;
use App\Http\Controllers\website\ProductController as WebsiteProductController;
use App\Http\Controllers\website\OfferController as WebsiteOfferController;
use App\Http\Controllers\website\UserController as WebsiteUserController;
use App\Http\Controllers\website\MemberShipController as WebsiteMemberShipController;
use App\Http\Controllers\website\OrderController as WebsiteOrderController;
use App\Http\Controllers\website\SearchController as WebsiteSearchController;



Route::get('/', [HomeController::class ,'index'])->middleware('loggin');
Route::get('/intro', [HomeController::class ,'intro'])->name('site.intro')->middleware('loggin');
Route::get('/login',function (){
    return 'login page';
})->name('login');
Route::group([
    'namespace' => 'website',
], function () {

    Route::group(['prefix' => 'Auth','namespace' => 'Auth'], function () {

        Route::get('/user/signup', [SignUpController::class ,'user_signup_page'])->name('user_signup_page');
        Route::get('/provider/signup', [SignUpController::class ,'provider_signup_page'])->name('provider_signup_page');
        Route::post('/contain_signUp', [SignUpController::class ,'contactFinancial'])->name('contain.signUp');
        Route::post('/register_user', [SignUpController::class ,'create_user'])->name('sign_up_user');
        Route::post('/register_provider', [SignUpController::class ,'create_provider'])->name('sign_up_provider');
        Route::get('/activation_code',[ResetPasswordController::class,'activationCode'])->name('activationCode');
        Route::post('/activation_code',[ResetPasswordController::class,'checkCode'])->name('checkCode');
        Route::post('/resend_code',[ResetPasswordController::class,'resendCode'])->name('resendCode');
        Route::get('/login',[loginController::class,'loginIndex'])->name('site.login');
        Route::post('/login',[loginController::class,'login'])->name('site.AuthLogin');
        Route::post('/log_out',[loginController::class,'logOut'])->name('site.AuthLogOut');
        Route::get('/forget_password',[ForgetPasswordController::class,'index'])->name('site.forgetPassword');
        Route::post('/change_password',[ForgetPasswordController::class,'changePassword'])->name('site.changePassword');
        Route::get('/edit_password',[ForgetPasswordController::class,'getEditPassword'])->name('site.getEditPassword');
        Route::post('/edit_password',[ForgetPasswordController::class,'editPassword'])->name('site.editPassword');
    });

    Route::group(['middleware' => 'AuthWebSite'], function () {
        Route::get('my_profile',[WebsiteUserController::class,'my_profile'])->name('my-profile-user');
        Route::get('provider_profile',[WebsiteUserController::class,'provider_profile'])->name('my-profile-provider');
        Route::post('update-profile/{user}',[WebsiteUserController::class,'update_profile'])->name('update_profile_user');
        Route::post('update-profile-provider/{user}',[WebsiteUserController::class,'update_profile_provider'])->name('update_profile_provider');

        Route::get('/notifications',[WebsiteUserController::class,'notifications'])->name('list_notifications');
    });

    Route::get('/search',[WebsiteSearchController::class,'index'])->name('site.search');
    Route::get('/search_items',[WebsiteSearchController::class,'show'])->name('site.searchItems');
    Route::get('/get_user',[WebsiteUserController::class,'getUserById'])->name('site.getUserById');

    Route::get('/categories',[CategoryController::class,'index'])->name('site.allCategories');
    Route::get('/category/{id}/details',[CategoryController::class,'show'])->name('site.sub.category');
    Route::get('/my_categories',[CategoryController::class,'my_categories'])->name('site.categories');
    Route::post('/store_categories',[CategoryController::class,'store'])->name('site.storeCategories');

    Route::group(['prefix' => 'setting'], function () {
        Route::get('/about_us',[SettingController::class,'aboutUs'])->name('site.aboutUs');
        Route::get('/terms',[SettingController::class,'terms'])->name('site.terms');
        Route::get('/contact_us',[SettingController::class,'contactUs'])->name('site.contactUs');
        Route::post('/contact_us',[SettingController::class,'sendContactUs'])->name('site.sendContactUs');
    });
});

Route::resource('products',WebsiteProductController::class);
Route::get('details-product/{product}',[WebsiteProductController::class,'details'])->name('details-product');
Route::post('products/uploadImage',[WebsiteProductController::class,'uploadImage'])->name('uploadImage_product');
Route::post('products/delete',[WebsiteProductController::class,'delete_product'])->name('delete_product');
Route::post('makeFavourite',[WebsiteProductController::class,'makeFavourite'])->name('site.makeFavourite')->middleware(['authUser']);
Route::get('list_favourite',[WebsiteProductController::class,'listFavourite'])->name('site.listFavourite');

Route::resource('offers',WebsiteOfferController::class);

Route::resource('member_ship',WebsiteMemberShipController::class);
Route::get('my_member_ship',[WebsiteMemberShipController::class,'my_member_ship'])->name('my_member_ship');

Route::resource('orders',WebsiteOrderController::class);
Route::post('orders/accepted_refuse/{order}',[WebsiteOrderController::class,'accepted_refuse'])->name('accepted_refuse_order');
Route::post('orders/finish/{order}',[WebsiteOrderController::class,'finish_order'])->name('finish_order');


Route::get('/sub_categories', [DeviceController::class,'sub_categories'])->name('getSub');
Route::post('check/column/exist',[DeviceController::class,'check_column'])->name('check.column.exist');
Route::get('/getNumberImage',[DeviceController::class,'getNumberImage'])->name('countImage');
Route::post('user/update/token',[DeviceController::class,'update_device'])->name('user.update.token');


Route::get("update_product_images",function (){

    $product = \App\Models\Product::find(12);

    $product->update(['images' => null,'images_path' => null]);

    $data = \App\Models\uploadImages::all();
    $data->each->delete();

    array_map('unlink', glob("files/products/*.*"));
});


Route::get('provider_users_now',function (){

    $users = \App\Models\User::where('is_user',1)->get();

    $users->each->update([
        'is_active' => 1,
        'payment' => 1,
        'accepted' => 1,
        'is_suspend' => 0,
    ]);
});

app/Models/MemberShip.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;

class MemberShip extends Model
{
       use Translatable;
       public $translatedAttributes = ['name'];
       protected $fillable = ['name','price','number_product','number_images',
				   'number_services_enjoy','number_category','period_start',
				   'period_end','is_suspend','message'];


    public function getImageAttribute($key){

        $file = URL('/').$key;
        if (file_exists($file)) {
            return $file;
        } else {
            return   URL('/') .  '/category.jpg';
        }
    }

       public function users(){

	    return $this->hasMany(Provider::class ,'member_id');
       }

}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Helpers\Images;
use App\Http\Requests\api\user\FavouriteValid;
use App\Http\Requests\api\user\rateProviderVaild;
use App\Http\Requests\vaildImage;
use App\Models\uploadImages;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class UserController extends MasterApiController
{

    public function __construct( private UserRepository $userRepository )
    {
        parent::__construct();

        $this->middleware('auth:api')->only(['rateProvider','makeOrUnFavourite','listFavourite','Notification']);
    }

    public function get_provider_by_id(Request $request){

        $data = $this->userRepository->show_provider($request);

        return $this->success("بيانات مزود الخدمة", $data);
    }

    public function rateProvider(rateProviderVaild $request){

       $this->userRepository->rate_provider($request);

        return $this->success(trans('global.rate_success'));
    }

    public function makeOrUnFavourite(FavouriteValid $request){

        $user = $request->user();

        if(!$user->favorites()->whereProviderId($request->providerId)->wherePivot('product_id',$request->productId)->first()){

            $user->favorites()->attach($request->providerId,['product_id'=>$request->productId]);

            return $this->success( trans('global.user_add_favorite'));
        }else {

            $user->favorites()->wherePivot('product_id', '=', $request->productId)->detach();

            return response()->json([
                'status' => 201,
                'message' =>  trans('global.user_remove_favorite')
            ]);
        }

    }

    public function listFavourite(Request $request){

       $data =  $this->userRepository->list_favourite($request);

        return $this->success("المفضلة",$data);
    }

    public function Notification(Request $request){

        $data = $this->userRepository->list_Notification($request);

        return $this->success("الإشعارات", $data);
    }

    public function upload_image(vaildImage $request){

        $my_upload = Images::uploadImage($request,'image','/files/uploads/');

        $image = uploadImages::create(['url' =>  '/files/uploads/' .$my_upload]);

       return $this->success("البيانات",$image);
    }

    public function remove_image(Request $request){

        if ($request->image && File::delete(public_path().$request->image)){

            $image = uploadImages::whereUrl($request->image)->first();

            if ($image){
                $image->delete();
            }
            return $this->success('تم مسح الملف بنجاح');
        }
        return $this->failure('غالبا مسار الملف غير صحيح');
    }

}

app/Http/Controllers/website/UserController.php
<?php

namespace App\Http\Controllers\website;

use App\Http\Controllers\Controller;
use App\Http\Requests\Auth\updateUserVaild;
use App\Models\City;
use App\Models\Provider;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class UserController extends Controller
{
    public function my_profile(){

        $user = Auth::user();

        $cities = City::whereIsSuspend(0)->get();

        return view('auth.user_profile',compact('user','cities'));
    }


    public function notifications(Request $request){
        $notification =  $request->user()->notifications;

        $current =     $notification->filter(function ($item) {
            return data_get($item, 'created_at') >= Carbon::today();
        })->values();

        $last =     $notification->filter(function ($item) {
            return data_get($item, 'created_at') < Carbon::today();
        })->values();

        return view('users.notifications',compact('current','last'));
    }

    public function provider_profile()
    {
        $user = Auth::user();
        $user->loadCount(['products','categories']);
        $user->load('provider','member');

        $cities = City::whereIsSuspend(0)->get();

        return view('auth.provider_profile',compact('user','cities'));
    }


    public function update_profile(updateUserVaild $request , User $user)
    {
        $user->fill($request->validated());
        if ($request->file('image')){
            $user->image = $this->upload_image($request, $user);
        }
        $user->save();

        return response()->json(['status' => 200,'message' => 'تم تعديل البيانات بنجاح']);
    }

    public function update_profile_provider(updateUserVaild $request , User $user)
    {
        $user->fill($request->validated());
        if ($request->file('image')){
            $user->image = $this->upload_image($request, $user);
        }
        $user->save();

        $data = [
            'facebook' => $request->facebook ? $request->facebook : $user->provider->facebook,
            'twitter' => $request->twitter ? $request->twitter : $user->provider->twitter,
            'snap_chat' => $request->snapChat ? $request->snapChat : $user->provider->snapChat,
            'connect_phone' =>  $request->phoneConnect ? 1: 0,
            'connect_email' =>  $request->emailConnect ? 1 : 0,
            'bank_transfer' =>  $request->bank ? 1 : 0,
            'pay' =>  $request->pay ? 1 : 0,
            'cash' =>  $request->cash ? 1 : 0,
            'pay_electronic' =>  $request->online ? 1: 0,
        ];
        $user->provider->update($data);

        return response()->json(['status' => 200,'message' => 'تم تعديل البيانات بنجاح']);
    }

    public function getUserById(Request $request){

        $user = User::with('provider','products')->findOrfail($request->id);

        $auth = $request->user();

        $products = $user['products'];

        $products->map(function ($q) use ($user,$auth){
            $q->isFavorite = $auth ? $auth->my_favorites()->wherePivot('product_id',$q->id)->first() ? 1 : 0 :0;
        });

        return view('users.get_user',compact('user','products'));
    }


    public function listFavourite(){

        $user = Auth::user();

        $products =   $user->filter_my_favorites();

        return view('products.favourite',compact('products'));
    }


    public  function makeFavourite(Request $request) {

        $user = $request->user();

        if(!$user->favorites()->whereProviderId($request->id)->wherePivot('product_id',$request->productId)->first()){

            $user->favorites()->attach($request->id,['product_id'=>$request->productId]);

            $message = trans('global.user_add_favorite');

        }else{

            $user->favorites()->wherePivot('product_id','=',$request->productId)->detach();

            $message = trans('global.user_remove_favorite');

        }

        session()->flash('success',  $message);

        return redirect()->back();
    }



    public function upload_image($request ,$user): string
    {
        $name = time() . '.' . $request->image->getClientOriginalName();
        $path  = public_path('/files/profile/' .$name);
        \Intervention\Image\Facades\Image::make($request->image)->resize(300, 300)->save($path);

        if ($user->image){
            $parse_url = parse_url($user->image);
            $path_old = public_path($parse_url['path']);
            if (\File::exists($path_old)):
                \File::delete($path_old);
            endif;
        }
        return  '/files/profile/' .$name;
    }

}

resources/views/users/get_user.blade.php
@extends('layouts.master')
@section('title', 'إدارة العملاء ')

@section('content')

    <body class="bg-provider text-center">
    <div class="container text-right  my-5 text-white ">
        <div class="row">
            <div class="col-xl-6 text-center">
                <img src="{{$user->image}}" class="img-fluid provider-img">
                <h4 class="default-color  py-3">
                    {{$user->name}}
                </h4>

                <span class="float-left default-color rate w-100">
                    <i class="fas fa-star"></i> {{$user->rate}}
                </span>
                <div>
                    <ul class="row provider-social pt-4 mx-auto w-75">
                        <li class="col-xl-2 col-2 bl-before">
                            <i class="fas fa-envelope"></i>
                        </li>
                        <li class="col-xl-2 col-2 bl-before">
                            <i class="fab fa-snapchat-ghost"></i>
                        </li>
                        <li class="col-xl-2 col-2 bl-before">
                            <i class="fab fa-facebook-f"></i>
                        </li>
                        <li class="col-xl-2 col-2 bl-before">
                            <i class="fas fa-phone"></i>
                        </li>
                        <li class="col-xl-2 col-2 ">
                            <i class="fab fa-twitter"></i>
                        </li>
                    </ul>

                </div>
            </div>
            <div class="col-xl-6 provider-services">
                <h5>المنتجات</h5>
                <ul class=" p-0">
                    @foreach($products as $product)
                        <li>

                              <form method="GET"  action="{{ route('orders.create')}}" id="changeProduct{{ $product->id }}">
                                <div class="card ">
                                    <div class="card-body p-0 card-body-img">
                                        <a href="#" onclick="return $('#changeProduct{{ $product->id }}').submit()">
                                            <input type="hidden" name="userId" value="{{$user->id}}">
                                            <input type="hidden" name="productId" value="{{$product->id}}">
                                            <img class="card-img" loading="lazy"alt="image_product"
                                                 src="@if ($product->images_path) {{$product->images_path[0]}} @else{{ asset('category.jpg') }}@endIf">
                                        </a>
                                    </div>
                                    <div class="card-body">
                                        <a href="#" onclick="return $('#changeProduct{{ $product->id }}').submit()">
                                            <h5 class="card-title default-color">{{$product->name}}</h5>
                                            <p class="card-text">
                                                {{$product->description}}
                                            </p>
                                        </a>
                                    </div>
                                </div>
                            </form>

                            @if(\Illuminate\Support\Facades\Auth::check())
                                <form method="post" class="myLoader"  action="{{ route('site.makeFavourite') }}" id="makeFavourite{{ $product->id }}">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="id" value="{{$user->id}}">
                                    <input type="hidden" name="productId" value="{{$product->id}}">
                                    <div class="card-body dir">
                                        <a href="javascript:;" class="heart" onclick="return $('#makeFavourite{{ $product->id }}').submit()" >
                                            <i class="fa fa-heart" @if($product->isFavorite == 1) style="color: red" @endif aria-hidden="true"></i>
                                        </a>
                                    </div>
                                </form>
                            @endif
                        </li>

                    @endforeach
                </ul>
            </div>
        </div>
    </div>
    @endsection
    @section('scripts')


        <script type="text/javascript">

            {{--function favourite($productId, $userId) {--}}
            {{--    var id = $userId;--}}
            {{--    var productId = $productId;--}}

            {{--    $.ajax({--}}
            {{--        type: 'POST',--}}
            {{--        url: '{{ route('site.makeFavourite') }}',--}}
            {{--        headers:{--}}
            {{--            'Accept' : 'application/json'--}}
            {{--        },--}}
            {{--        data: {--}}
            {{--            id: id,--}}
            {{--            productId: productId--}}
            {{--        },--}}
            {{--        dataType: 'json',--}}
            {{--        beforeSend:function () {--}}
            {{--            $(".hiddenContent").toggle();--}}
            {{--            $(".hiddenLoading").toggle();--}}
            {{--        },--}}
            {{--        cache: false,--}}
            {{--        success: function (data) {--}}
            {{--            if (data.status == 200) {--}}

            {{--                var shortCutFunction = 'success';--}}
            {{--                var msg = data.message;--}}
            {{--                var title = 'نجاح';--}}
            {{--                toastr.options = {--}}
            {{--                    positionClass: 'toast-top-left',--}}
            {{--                    onclick: null--}}
            {{--                };--}}
            {{--                var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists--}}
            {{--                $toastlast = $toast;--}}

            {{--            }--}}

            {{--            if (data.status == 400) {--}}
            {{--                var shortCutFunction = 'error';--}}
            {{--                var msg = data.error[0];--}}
            {{--                var title = 'خطأ';--}}
            {{--                toastr.options = {--}}
            {{--                    positionClass: 'toast-top-left',--}}
            {{--                    onclick: null--}}
            {{--                };--}}
            {{--                var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists--}}
            {{--                $toastlast = $toast;--}}

            {{--            }--}}
            {{--        },--}}
            {{--        complete: function () {--}}
            {{--            $(".hiddenLoading").toggle();--}}
            {{--            $(".hiddenContent").toggle();--}}
            {{--        }--}}
            {{--    });--}}

            {{--}--}}


        </script>

@endsection

resources/views/users/notifications.blade.php
@extends('layouts.master')
@section('title', 'إدارة العملاء ')

@section('content')

    <body class="bg-orders text-center">

    <div class="container text-right  my-5 text-white">
    @if(count($current) > 0 || count($last) > 0 )
        <!-- new notification -->
            @if(count($current) > 0)
                <div class="new-not">
                    <h5>تنبيهات جديدة</h5>
                    <ul class="row">
                        @foreach($current as $value)
                            <li class=" col-xl-4 col-lg-6 col-md-6">
                                <div class="order">

                                    <a href="@if($value->order){{route('orders.show',$value->order->id)}} @else#@endif" @if($value->order) target="_blank" @endif>
                                        <span class="time text-secondary ">{{$value->created_at->diffForHumans()}}  </span>
                                        <h5 class="default-color">{{$value->title}}</h5>
                                        <p class="text-white">{{$value->body}}</p>
                                    </a>
                                </div>
                            </li>
                        @endforeach
                    </ul>
                </div>
            @endif
        <!-- old notification -->
            @if(count($last) > 0)
                <div class="old-not">
                    <h5>تنبيهات سابقه</h5>
                    <ul class="row">
                        @foreach($last as $value)
                            <li class=" col-xl-4 col-lg-6 col-md-6">
                                <div class="order">
                                    <a href="@if($value->order){{route('orders.show',$value->order->id)}} @else#@endif" target="_blank">
                                        <span class="time text-secondary ">{{$value->created_at->diffForHumans()}}  </span>
                                        <h5 class="default-color">{{$value->title}}</h5>
                                        <p class="text-white">{{$value->body}}</p>
                                    </a>
                                </div>
                            </li>
                        @endforeach
                    </ul>
                </div>
            @endif
        @else
            <img loading="lazy" style="width: inherit" src="{{ asset('empty_data.png')  }}">
        @endif
    </div>
@endsection