routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\HomeController;
use App\Http\Controllers\website\Auth\SignUpController;
use App\Http\Controllers\website\Auth\ResetPasswordController;
use App\Http\Controllers\website\Auth\loginController;
use App\Http\Controllers\website\Auth\ForgetPasswordController;
use App\Http\Controllers\website\DeviceController;
use App\Http\Controllers\website\CategoryController;
use App\Http\Controllers\website\SettingController;
use App\Http\Controllers\website\ProductController as WebsiteProductController;
use App\Http\Controllers\website\OfferController as WebsiteOfferController;
use App\Http\Controllers\website\UserController as WebsiteUserController;
use App\Http\Controllers\website\MemberShipController as WebsiteMemberShipController;
use App\Http\Controllers\website\OrderController as WebsiteOrderController;
use App\Http\Controllers\website\SearchController as WebsiteSearchController;



Route::get('/', [HomeController::class ,'index'])->middleware('loggin');
Route::get('/intro', [HomeController::class ,'intro'])->name('site.intro')->middleware('loggin');
Route::get('/login',function (){
    return 'login page';
})->name('login');
Route::group([
    'namespace' => 'website',
], function () {

    Route::group(['prefix' => 'Auth','namespace' => 'Auth'], function () {

        Route::get('/user/signup', [SignUpController::class ,'user_signup_page'])->name('user_signup_page');
        Route::get('/provider/signup', [SignUpController::class ,'provider_signup_page'])->name('provider_signup_page');
        Route::post('/contain_signUp', [SignUpController::class ,'contactFinancial'])->name('contain.signUp');
        Route::post('/register_user', [SignUpController::class ,'create_user'])->name('sign_up_user');
        Route::post('/register_provider', [SignUpController::class ,'create_provider'])->name('sign_up_provider');
        Route::get('/activation_code',[ResetPasswordController::class,'activationCode'])->name('activationCode');
        Route::post('/activation_code',[ResetPasswordController::class,'checkCode'])->name('checkCode');
        Route::post('/resend_code',[ResetPasswordController::class,'resendCode'])->name('resendCode');
        Route::get('/login',[loginController::class,'loginIndex'])->name('site.login');
        Route::post('/login',[loginController::class,'login'])->name('site.AuthLogin');
        Route::post('/log_out',[loginController::class,'logOut'])->name('site.AuthLogOut');
        Route::get('/forget_password',[ForgetPasswordController::class,'index'])->name('site.forgetPassword');
        Route::post('/change_password',[ForgetPasswordController::class,'changePassword'])->name('site.changePassword');
        Route::get('/edit_password',[ForgetPasswordController::class,'getEditPassword'])->name('site.getEditPassword');
        Route::post('/edit_password',[ForgetPasswordController::class,'editPassword'])->name('site.editPassword');
    });

    Route::group(['middleware' => 'AuthWebSite'], function () {
        Route::get('my_profile',[WebsiteUserController::class,'my_profile'])->name('my-profile-user');
        Route::get('provider_profile',[WebsiteUserController::class,'provider_profile'])->name('my-profile-provider');
        Route::post('update-profile/{user}',[WebsiteUserController::class,'update_profile'])->name('update_profile_user');
        Route::post('update-profile-provider/{user}',[WebsiteUserController::class,'update_profile_provider'])->name('update_profile_provider');

        Route::get('/notifications',[WebsiteUserController::class,'notifications'])->name('list_notifications');
    });

    Route::get('/search',[WebsiteSearchController::class,'index'])->name('site.search');
    Route::get('/search_items',[WebsiteSearchController::class,'show'])->name('site.searchItems');
    Route::get('/get_user',[WebsiteUserController::class,'getUserById'])->name('site.getUserById');

    Route::get('/categories',[CategoryController::class,'index'])->name('site.allCategories');
    Route::get('/category/{id}/details',[CategoryController::class,'show'])->name('site.sub.category');
    Route::get('/my_categories',[CategoryController::class,'my_categories'])->name('site.categories');
    Route::post('/store_categories',[CategoryController::class,'store'])->name('site.storeCategories');

    Route::group(['prefix' => 'setting'], function () {
        Route::get('/about_us',[SettingController::class,'aboutUs'])->name('site.aboutUs');
        Route::get('/terms',[SettingController::class,'terms'])->name('site.terms');
        Route::get('/contact_us',[SettingController::class,'contactUs'])->name('site.contactUs');
        Route::post('/contact_us',[SettingController::class,'sendContactUs'])->name('site.sendContactUs');
    });
});

Route::resource('products',WebsiteProductController::class);
Route::get('details-product/{product}',[WebsiteProductController::class,'details'])->name('details-product');
Route::post('products/uploadImage',[WebsiteProductController::class,'uploadImage'])->name('uploadImage_product');
Route::post('products/delete',[WebsiteProductController::class,'delete_product'])->name('delete_product');
Route::post('makeFavourite',[WebsiteProductController::class,'makeFavourite'])->name('site.makeFavourite')->middleware(['authUser']);
Route::get('list_favourite',[WebsiteProductController::class,'listFavourite'])->name('site.listFavourite');

Route::resource('offers',WebsiteOfferController::class);

Route::resource('member_ship',WebsiteMemberShipController::class);
Route::get('my_member_ship',[WebsiteMemberShipController::class,'my_member_ship'])->name('my_member_ship');

Route::resource('orders',WebsiteOrderController::class);
Route::post('orders/accepted_refuse/{order}',[WebsiteOrderController::class,'accepted_refuse'])->name('accepted_refuse_order');
Route::post('orders/finish/{order}',[WebsiteOrderController::class,'finish_order'])->name('finish_order');


Route::get('/sub_categories', [DeviceController::class,'sub_categories'])->name('getSub');
Route::post('check/column/exist',[DeviceController::class,'check_column'])->name('check.column.exist');
Route::get('/getNumberImage',[DeviceController::class,'getNumberImage'])->name('countImage');
Route::post('user/update/token',[DeviceController::class,'update_device'])->name('user.update.token');


Route::get("update_product_images",function (){

    $product = \App\Models\Product::find(12);

    $product->update(['images' => null,'images_path' => null]);

    $data = \App\Models\uploadImages::all();
    $data->each->delete();

    array_map('unlink', glob("files/products/*.*"));
});


Route::get('provider_users_now',function (){

    $users = \App\Models\User::where('is_user',1)->get();

    $users->each->update([
        'is_active' => 1,
        'payment' => 1,
        'accepted' => 1,
        'is_suspend' => 0,
    ]);
});

app/Models/Product.php
<?php

namespace App\Models;

use App\Traits\CanBeScoped;
use Astrotomic\Translatable\Translatable;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use Translatable , CanBeScoped , SoftDeletes;
    public $translatedAttributes = ['name', 'description'];
    protected $fillable = ['name', 'description','category_id','user_id' ,'price','images','images_path'];

    protected $casts = [ 'images' => 'array' ,'images_path' => 'array'];

    protected $hidden = ['translations'];

    public function user() {

	    return $this->belongsTo(User::class);
    }

    public function user_filter(){
	    return $this->belongsTo(User::class,'user_id')
		  		->select('id','name','email','phone','image');
    }



      public function provider()
      {
	     return $this->belongsTo(Provider::class,'user_id');
      }


       public function orders()
       {
        return $this->hasMany(Order::class);
       }

//       public function images()
//       {
//        return $this->hasMany(Image::class);
//       }

       public function category()
       {
        return $this->belongsTo(Category::class);
       }


        public function offer(){
	    return $this->hasOne(Offer::class)->whereStatus(0);
       }

         public function offer_filter(){
    	    return $this->hasOne(Offer::class)->whereStatus(0)->select('product_id','price','period_start','period_end');
       }

    public function active_offer()
    {
        return $this->offer()->whereDate('period_end','>=',Carbon::today());
    }

//    public function subscriptions()
//    {
//        return $this->belongsToMany(Subscription::class, 'product_subscription' ,'product_id','subscription_id');
//    }
}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\api\product\deleteVaild;
use App\Http\Requests\api\product\storeVaild;
use App\Http\Requests\api\product\updateVaild;
use App\Models\Product;
use App\Repositories\ProductRepository;
use Illuminate\Http\Request;

class ProductController extends MasterApiController
{
    public function __construct( private ProductRepository $productRepository)
    {
        parent::__construct();

        $this->middleware('auth:api')->except(['index','show']);
    }

    public function index(Request $request){

        $data =  $this->productRepository->list($request);

        return response()->json( [
            'status' => 200 ,
            'countProduct' => $data['countProduct'],
            'countProductRemaining' => $data['countProductRemaining'],
            'data' =>  $data['data'] ,
        ] , 200 );
    }

    public function show(Request $request,Product $product){

        $data =  $this->productRepository->show($request , $product);

        return $this->success("بيانات المنتج", $data);
    }

    public function store(storeVaild $request){

        $data = $this->productRepository->store($request);

        return  $this->success(trans('global.product_added'),$data);
    }

    public function update(updateVaild $request,Product $product){

         $data = $this->productRepository->update($request,$product);

        return  $this->success(trans('global.product_edit'),$data);
    }

    public function destroy(deleteVaild $request , Product $product){

        $this->productRepository->delete($product);

        return  $this->success(trans('global.product_delete'));
    }

}

resources/views/products/create.blade.php
@extends('layouts.master')
@section('title', 'إدارة العملاء ')

@section('styles')
    <style>

        .hidden-category{
            visibility: hidden !important;
        }
        .help-block {
            color: #e74c3c !important;
            font-size: 16px !important;

        }

    </style>
@endsection

@section('content')

<body class="bg-orders text-center">

    <!-- content -->
    <div class="container text-right my-5 text-white">
        <div class="row">
            <div class="col-xl-4 mb-5">
                <h6 class="pb-3">معلومات الاشتراك</h6>

                <div class="order default-color text-center">
                    <h6>رصيد منتجاتك</h6>
                    <div class="row ">
                        <div class="col-xl-6 col-6 bl-before">
                            @if(isset($countproductHave))
                                <h1>{{$countproductHave}}</h1>
                            @endif
                            <span class="text-white">منتجات معروضة</span>
                        </div>
                        <div class="col-xl-6 col-6">
                            @if(isset($countproductRemind))
                                <h1>{{$countproductRemind}}</h1>
                            @endif
                            <span class="text-white">منتجات متبقية</span>
                        </div>
                    </div>
                    <p class="text-white">
                        لتتمكن من عرض منتجات وخدمات اكثر بامكانك تحديث اشتراكك
                    </p>
                    <a href="" class="default-color"> عرض الاشتراكات </a>
                </div>

            </div>
            <div class="col-xl-8">
            <form method="post" id="dynamicFormSubmit" class="product-info" action="{{route('products.store') }}" enctype="multipart/form-data" data-parsley-validate novalidate>
                {{ csrf_field() }}
                <div class="row">

                    <div class="col-xl-6 mb-5">
                        <h6 class="pb-3">صور المنتج (بامكانك اضافة حتى 5 صور)</h6>
                        @for ($i = 0; $i < 5; $i++)
                            <div class="wrap-custom-file">
                                <input type="file" name="images[]" class="choose_image"  id="image{{$i}}" accept="image/png,image/jpeg,image/jpg" />
                                <label for="image{{$i}}" id="image{{$i}}">
                                    <img src="{{ asset('Site/images/icons/prf_add_photo.png')  }}"
                                         id="add{{$i}}">
                                </label>

                            </div>
                        @endfor
                    </div>

                    <div class="col-xl-6 mb-5">
                        <h6 class="pb-3">معلومات المنتج</h6>
                        <form action="" class="product-info">
                            <div class="form-group">
                                <input name="product_name" value="{{old('product_name')}}" type="text" required class="form-control requiredField" placeholder="اسم المنتج / الخدمة">
                            </div>
                            <div class="form-group">
                                <div class="form-group">
                                    <select  name="category" class="form-control requiredField category" required>
                                        <option value="" disabled selected hidden class="text-white">القسم الرئيسي</option>
                                        @foreach($categories as $item)
                                            <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group sub-section ">

                                <select name="category" class="form-control hideDiv City_chid">
                                    <option value="" disabled selected hidden class="text-white">القسم الفرعي</option>
                                </select>

                            </div>
                            <div class="form-group sub-section float-left ">

                                <select name="category" class="form-control hideDiv Child_City_chid">
                                    <option value="" disabled selected hidden class="text-white">القسم الفرعي</option>
                                </select>

                            </div>
                            <div class="form-group">
                                <input name="description" value="{{old('description')}}" required type="text" class="form-control requiredField" placeholder="الوصف">
                            </div>
                            <div class="form-group">
                                <input name="price" value="{{old('price')}}" type="text" required class="form-control requiredField" placeholder="السعر">
                                <span class="currency">ريال سعودي</span>
                            </div>
                        </form>
                    </div>
                    <div class="col-xl-12 text-center my-5 add-pro-btn">
                        <button type="submit" id="hiddenButton" class="btn default-bg br-50 text-dark mx-2 my-2">اضافة المنتج</button>
                        <a class="btn provider-btn br-50 mx-2 my-2">الغاء</a>
                    </div>
                </div>

            </form>
            </div>
        </div>

    </div>
@endsection

@section('scripts')
        <script src="{{asset('website_scripts/categories&sub.js')}}" defer></script>
        <script src="{{asset('website_scripts/imagesVaildation.js')}}" defer></script>
        <script src="{{asset('website_scripts/dynamicFormSubmit.js')}}" defer></script>

@endsection

resources/views/products/details.blade.php
@extends('layouts.master')
@section('title', 'إدارة العملاء ')
@section('styles')
    <link rel="stylesheet" href="{{asset('Site/css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{asset('Site/css/owl.theme.default.min.css')}}">
    <style>
        #productImages .owl-item img {
            display: block;
            width: 100%;
            height: 400px;
            border-radius: 40px;
        }

    </style>
@endsection
@section('content')
    <body class="bg-orders text-center">

    <!-- content -->
    <div class="container text-right my-5 text-white">
        <div class="row">
            <div class="col-md-6">
                <div class="owl-carousel owl-theme " id="productImages">
                    @if($product->images_path)
                        @foreach($product->images_path as $image)
                            <div class="item ">
                                <img src="{{ $image }}" class="img-fluid br-5" alt="">
                            </div>
                        @endforeach
                    @else
                        <div class="item ">
                            <img src="{{asset('Site/images/pic/1.jpeg')}}" class="img-fluid br-5" alt="صورة">
                        </div>
                    @endif
                </div>
            </div>
            <div class="col-md-6">
                <div class="my-subscripe h-100">
                    <h4 class="pb-3  default-color">
                             اسم المنتج / الخدمة : {{$product->name}}
                    </h4>
                    <h5 class="text-white">
                          القسم الرئيسي :  {{$product->category->parent->parent->name ?? $product->category->parent->name ?? $product->category->name }}
                    </h5>
                    <h5 class="text-white">
                        القسم الفرعي {{optional($product->category->parent)->parent ?
                                                    optional($product->category->parent) ?
                                                        optional($product->category->parent)->name
                                                    : $product->category->name
                                       : $product->category->name}}
                    </h5>
                    @if( optional($product->category->parent)->parent  && optional($product->category->parent)  )
                        <h5 class="text-white">
                            القسم الفرعي فرعي :{{$product->category->name  }}
                        </h5>
                    @endif
                    <p class="card-text pt-3">{{$product->description}} </p>
                    <h1 class="font-weight-bold default-color">{{$product->price}} ريال</h1>
                </div>
            </div>
        </div>

    </div>


@endsection

@section('scripts')

        <script src="{{asset('Site/js/slick.min.js')}}"></script>
        <script src="{{asset('Site/js/owl.carousel.min.js')}}"></script>
        <script>
            $(document).ready(function() {
                // ======================== productImages==========================

                $('#productImages').owlCarousel({
                    loop: true,
                    items: 1,
                    center: false,
                    margin: 20,
                    nav: false,
                    dots: false,
                    rtl: true,
                    autoplay: false,
                    autoplayTimeout: 1000,
                    autoplayHoverPause: true,

                })
            });
        </script>
@endsection

resources/views/products/favourite.blade.php
@extends('layouts.master')
@section('title', 'إدارة العملاء ')

@section('content')
<body class="bg-provider text-center">

    <div class="container text-right  my-5 text-white ">
        <div>
            @if(count($products) > 0)
            <ul class="row p-0 provider-services">
                @foreach($products as $product)
                    <li class="col-xl-6 ">
{{--                    <a href="{{route('orders.create')}}?productId={{$product->id}}&userId={{$product->user_id}}">--}}
                    <a href="{{route('details-product',$product->id)}}">
                        <input type="hidden" value="{{$product->id}}" name="productId">
                        <div class="card ">
                            <div class="card-body p-0 card-body-img">
                                <img class="card-img" src="{{$product->images_path ? $product->images_path[0] : asset('category.jpg') }}" alt="">
                            </div>
                            <div class="card-body">
                                <div class="card-title default-color">
                                    <span>{{$product->name}}</span> - <span>{{$product->user->name}}</span>
                                </div>
                                <p class="card-text">
                                    {{$product->description}}
                                </p>
                            </div>
                            <div class="card-body dir">
                                <i class="fas fa-chevron-left"></i>
                            </div>
                        </div>
                    </a>
                </li>
                @endforeach
            </ul>
            @else
                <img src="{{asset('empty_data.png')}}" alt="">
            @endif
        </div>

    </div>

@endsection

resources/views/products/index.blade.php
@extends('layouts.master')
@section('title', 'إدارة العملاء ')

@section('content')
<body class="bg-orders text-center">

    <!-- content -->
    <div class="container text-right my-5 text-white">
        <div class="row">
            <div class="col-xl-4">
                <h6>معلومات الاشتراك </h6>

                <div class="order default-color text-center">
                    <h6>رصيد منتجاتك</h6>
                    <div class="row ">
                        <div class="col-xl-6 col-6 bl-before">
                            @if(isset($countproductHave))
                                <h1>{{$countproductHave}}</h1>
                            @endif
                            <span class="text-white">منتجات معروضة</span>
                        </div>
                        <div class="col-xl-6 col-6">
                            @if(isset($countproductRemind))
                                <h1>{{$countproductRemind}}</h1>
                            @endif
                            <span class="text-white">منتجات متبقية</span>
                        </div>
                    </div>
                    <p class="text-white">
                        لتتمكن من عرض منتجات وخدمات اكثر بامكانك تحديث اشتراكك
                    </p>
                    <a href="" class="default-color"> عرض الاشتراكات </a>
                </div>

            </div>
            <div class="col-xl-4">
                @if(count($products) > 0)
                    <h6>منتجاتي</h6>

                    <ul>
                        @foreach($products as $product)
                            <li>
                                <form method="GET" action="{{ route('products.show',$product->id) }}"  id="changeProduct{{ $product->id }}" >

                                    <a href="#" onclick="return $('#changeProduct{{ $product->id }}').submit()">
                                        <input type="hidden" name="productId" value="{{$product->id}}">
                                        <div class="card ">
                                            @if($product->images_path)
                                            <img class="card-img" src="{{$product->images_path[0] }}" alt="">
                                            @endif
                                            <div class="card-body">
                                                <h5 class="card-title default-color"> {{$product->name}}    </h5>
                                                <p class="card-text">
                                                    {{$product->description}}
                                                </p>
                                            </div>
                                        </div>
                                    </a>
                                </form>
                            </li>
                        @endforeach
                    </ul>
                <div class="proPagination">

                    {{ $products->links('vendor.pagination.simple-bootstrap-4') }}
                </div>
                @else
                    <div>لا تملك منتجات </div>
               @endif

            </div>
            <div class="col-xl-4">
                {{--<h6>المنتجات المتبقية</h6>--}}
                <br>
                <ul>
                    <li>
                        <a  href="{{route('products.create')}}" target="_blank">
                            <div class="card ">
                                <div class="card-plus">
                                    <i class="fas fa-plus"></i>
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title default-color mt-4">اضافة منتج جديد</h5>
                                </div>
                            </div>
                        </a>
                    </li>

                </ul>
            </div>
        </div>

    </div>

@endsection