routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\HomeController;
use App\Http\Controllers\website\Auth\SignUpController;
use App\Http\Controllers\website\Auth\ResetPasswordController;
use App\Http\Controllers\website\Auth\loginController;
use App\Http\Controllers\website\Auth\ForgetPasswordController;
use App\Http\Controllers\website\DeviceController;
use App\Http\Controllers\website\CategoryController;
use App\Http\Controllers\website\SettingController;
use App\Http\Controllers\website\ProductController as WebsiteProductController;
use App\Http\Controllers\website\OfferController as WebsiteOfferController;
use App\Http\Controllers\website\UserController as WebsiteUserController;
use App\Http\Controllers\website\MemberShipController as WebsiteMemberShipController;
use App\Http\Controllers\website\OrderController as WebsiteOrderController;
use App\Http\Controllers\website\SearchController as WebsiteSearchController;



Route::get('/', [HomeController::class ,'index'])->middleware('loggin');
Route::get('/intro', [HomeController::class ,'intro'])->name('site.intro')->middleware('loggin');
Route::get('/login',function (){
    return 'login page';
})->name('login');
Route::group([
    'namespace' => 'website',
], function () {

    Route::group(['prefix' => 'Auth','namespace' => 'Auth'], function () {

        Route::get('/user/signup', [SignUpController::class ,'user_signup_page'])->name('user_signup_page');
        Route::get('/provider/signup', [SignUpController::class ,'provider_signup_page'])->name('provider_signup_page');
        Route::post('/contain_signUp', [SignUpController::class ,'contactFinancial'])->name('contain.signUp');
        Route::post('/register_user', [SignUpController::class ,'create_user'])->name('sign_up_user');
        Route::post('/register_provider', [SignUpController::class ,'create_provider'])->name('sign_up_provider');
        Route::get('/activation_code',[ResetPasswordController::class,'activationCode'])->name('activationCode');
        Route::post('/activation_code',[ResetPasswordController::class,'checkCode'])->name('checkCode');
        Route::post('/resend_code',[ResetPasswordController::class,'resendCode'])->name('resendCode');
        Route::get('/login',[loginController::class,'loginIndex'])->name('site.login');
        Route::post('/login',[loginController::class,'login'])->name('site.AuthLogin');
        Route::post('/log_out',[loginController::class,'logOut'])->name('site.AuthLogOut');
        Route::get('/forget_password',[ForgetPasswordController::class,'index'])->name('site.forgetPassword');
        Route::post('/change_password',[ForgetPasswordController::class,'changePassword'])->name('site.changePassword');
        Route::get('/edit_password',[ForgetPasswordController::class,'getEditPassword'])->name('site.getEditPassword');
        Route::post('/edit_password',[ForgetPasswordController::class,'editPassword'])->name('site.editPassword');
    });

    Route::group(['middleware' => 'AuthWebSite'], function () {
        Route::get('my_profile',[WebsiteUserController::class,'my_profile'])->name('my-profile-user');
        Route::get('provider_profile',[WebsiteUserController::class,'provider_profile'])->name('my-profile-provider');
        Route::post('update-profile/{user}',[WebsiteUserController::class,'update_profile'])->name('update_profile_user');
        Route::post('update-profile-provider/{user}',[WebsiteUserController::class,'update_profile_provider'])->name('update_profile_provider');

        Route::get('/notifications',[WebsiteUserController::class,'notifications'])->name('list_notifications');
    });

    Route::get('/search',[WebsiteSearchController::class,'index'])->name('site.search');
    Route::get('/search_items',[WebsiteSearchController::class,'show'])->name('site.searchItems');
    Route::get('/get_user',[WebsiteUserController::class,'getUserById'])->name('site.getUserById');

    Route::get('/categories',[CategoryController::class,'index'])->name('site.allCategories');
    Route::get('/category/{id}/details',[CategoryController::class,'show'])->name('site.sub.category');
    Route::get('/my_categories',[CategoryController::class,'my_categories'])->name('site.categories');
    Route::post('/store_categories',[CategoryController::class,'store'])->name('site.storeCategories');

    Route::group(['prefix' => 'setting'], function () {
        Route::get('/about_us',[SettingController::class,'aboutUs'])->name('site.aboutUs');
        Route::get('/terms',[SettingController::class,'terms'])->name('site.terms');
        Route::get('/contact_us',[SettingController::class,'contactUs'])->name('site.contactUs');
        Route::post('/contact_us',[SettingController::class,'sendContactUs'])->name('site.sendContactUs');
    });
});

Route::resource('products',WebsiteProductController::class);
Route::get('details-product/{product}',[WebsiteProductController::class,'details'])->name('details-product');
Route::post('products/uploadImage',[WebsiteProductController::class,'uploadImage'])->name('uploadImage_product');
Route::post('products/delete',[WebsiteProductController::class,'delete_product'])->name('delete_product');
Route::post('makeFavourite',[WebsiteProductController::class,'makeFavourite'])->name('site.makeFavourite')->middleware(['authUser']);
Route::get('list_favourite',[WebsiteProductController::class,'listFavourite'])->name('site.listFavourite');

Route::resource('offers',WebsiteOfferController::class);

Route::resource('member_ship',WebsiteMemberShipController::class);
Route::get('my_member_ship',[WebsiteMemberShipController::class,'my_member_ship'])->name('my_member_ship');

Route::resource('orders',WebsiteOrderController::class);
Route::post('orders/accepted_refuse/{order}',[WebsiteOrderController::class,'accepted_refuse'])->name('accepted_refuse_order');
Route::post('orders/finish/{order}',[WebsiteOrderController::class,'finish_order'])->name('finish_order');


Route::get('/sub_categories', [DeviceController::class,'sub_categories'])->name('getSub');
Route::post('check/column/exist',[DeviceController::class,'check_column'])->name('check.column.exist');
Route::get('/getNumberImage',[DeviceController::class,'getNumberImage'])->name('countImage');
Route::post('user/update/token',[DeviceController::class,'update_device'])->name('user.update.token');


Route::get("update_product_images",function (){

    $product = \App\Models\Product::find(12);

    $product->update(['images' => null,'images_path' => null]);

    $data = \App\Models\uploadImages::all();
    $data->each->delete();

    array_map('unlink', glob("files/products/*.*"));
});


Route::get('provider_users_now',function (){

    $users = \App\Models\User::where('is_user',1)->get();

    $users->each->update([
        'is_active' => 1,
        'payment' => 1,
        'accepted' => 1,
        'is_suspend' => 0,
    ]);
});

app/Models/Offer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Offer extends Model
{

    protected $fillable = ['product_id' , 'price','period_start','period_end'];

    public function product(){
       return $this->belongsTo(Product::class);
    }



}

app/Http/Controllers/Api/OfferController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\api\offer\offerDeleteVaild;
use App\Http\Requests\api\offer\offerStoreVaild;
use App\Http\Requests\api\offer\offerUpdateVaild;
use App\Models\Offer;
use App\Repositories\OfferRepository;
use Illuminate\Http\Request;

class OfferController extends MasterApiController
{
    public function __construct( private OfferRepository $offerRepository)
    {
        parent::__construct();

        $this->middleware('auth:api')->except(['index','show']);
    }

    public function index(Request $request){

        $data = $this->offerRepository->list($request);

        return response()->json( [
            'status' => 200 ,
            'countOffer' => $data['countOffer'],
            'countOfferRemaining' => $data['countOfferRemaining'],
            'data' => $data['data'] ,
        ] , 200 );
    }

    public function show(){

    }

    public function store(offerStoreVaild $request){

        $data = $this->offerRepository->store($request);

        return $this->success(trans('global.offer_add'), $data);
    }

    public function update(offerUpdateVaild $request , Offer $offer){

        $data = $this->offerRepository->update($request, $offer);

        return $this->success(trans('global.offer_edit'), $data);
    }

    public function destroy(offerDeleteVaild $request ,Offer $offer){

         $this->offerRepository->cancel_offer($offer);

        return $this->success(trans('global.offer_delete'));
    }

}

app/Http/Controllers/website/OfferController.php
<?php

namespace App\Http\Controllers\website;

use App\Http\Controllers\Controller;
use App\Http\Requests\Products\StoreOfferVaild;
use App\Models\Offer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OfferController extends Controller
{
    public function __construct()
    {
        $this->middleware(['AuthWebSite','acceptedOrHaveMemberShip']);
    }

    public function index(){
        $user = Auth::user();

        $products = $user->my_products;

        if ($products->count() == 0){
            session()->flash('my_errors',  ' لا يوجد منتجات لإضافة عروض');
            return   redirect()->back();
        }

        return view('offers.index',compact('products'));
    }

    public function store(StoreOfferVaild $request){

        $offer = Offer::create($request->validated());

        return response()->json(['status' => 200,'url' => route('offers.index')]);
    }
}

resources/views/offers/index.blade.php
@extends('layouts.master')
@section('title', 'إدارة العملاء ')

@section('content')

    <body class="bg-offers text-center">

    <div class="container text-right  my-5 text-white">
        @if(count($products) > 0)
            <form id="dynamicFormSubmit" method="post" class="product-info" action="{{route('offers.store') }}"
                  enctype="multipart/form-data" data-parsley-validate novalidate>
                {{ csrf_field() }}
                <div>
                    <h6>اختر احدى منتجاتك لوضع عرض عليها</h6>
                    <ul class="row p-0 choose-offer btn-group btn-group-toggle" data-toggle="buttons">

                        @foreach($products as $product)
                            <li class="col-xl-4 valueProduct col-lg-6 btn btn-secondary waves-effect waves-light">
                                <input type="radio" name="product_id" id="option{{$product->id}}" autocomplete="off" value="{{$product->id}}">
                                <a href="#">
                                    <div class="card ">
                                        @if($product->images_path)
                                            <img class="card-img" src="{{$product->images_path[0] }}" alt="">
                                        @else
                                            <img class="card-img" src="{{asset('category.jpg') }}" alt="">
                                        @endif
                                        <div class="card-body">
                                            <h5 class="card-title default-color">{{$product->name}}  </h5>
                                            <p class="card-title default-color">سعر المنتج {{$product->price}} </p>
                                            <p class="card-text">
                                                {{$product->description}}
                                            </p>
                                        </div>
                                    </div>
                                </a>
                            </li>
                        @endforeach
                    </ul>
                    <div>
                        <div class="text-center my-5 new-offer">
                            <div class="form-group new-price">
                                <input type="text" name="price" class="form-control" placeholder=" السعرالجديد" required>
                                <span class="currency">ريال سعودي</span>
                            </div>
                            <div class="form-group new-price mt-4"  >
                                <input type="text" onfocus="(this.type='date')" name="period_start" class="form-control text-right" placeholder="تاريخ بداية العرض"   required>
                                <!--<input type="date" name="period_start"  class="form-control form_datetime" placeholder="تاريخ بداية العرض"   required>-->
                                <!--<i class="fas fa-calendar-alt form-icon"></i>-->
                            </div>
                             <div class="form-group new-price mt-4">
                             <input type="text" onfocus="(this.type='date')" name="period_end"   class="form-control text-right" placeholder="تاريخ نهاية العرض" required>
                                <!--<input type="date" name="period_end" class="form-control form_datetime" placeholder="تاريخ نهاية العرض" required >-->
                                <!--<i class="fas fa-calendar-alt form-icon"></i>-->
                            </div>
                        </div>

                    </div>

                </div>
                <div class="col-xl-12 text-center my-5 ">
                    <button id="myButton" type="submit" class="btn default-bg br-50 text-dark my-5 px-4">اضافة العرض</button>
                </div>

            </form>
        @endif
    </div>
    @endsection

    @section('scripts')
        <script type="text/javascript">
            $(document).ready(function(){
                $(".form_datetime").datepicker({format: 'yyyy-mm-dd'});
            });

            $( "#myButton" ).click(function() {
                var value = $('.valueProduct').hasClass('active');

                if(value === false){
                    showErrors('{{ session()->get('errors',' يجب اختيار منتج من فضلك  ') }}');
                    return false;
                }
            });
        </script>

        <script src="{{asset('website_scripts/dynamicFormSubmit.js')}}" defer></script>

@endsection